// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uocqgeahfighgfnkwhyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvY3FnZWFoZmlnaGdmbmt3aHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzg3OTYsImV4cCI6MjA2MDYxNDc5Nn0.YuV4USNIZB3T3xrz2L393nPekO5x-rLxPZb3k0gDL_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);